version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn pastebinir.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./static:/static
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/privkey.pem
    depends_on:
      - web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             celery -A pastebinir worker --loglevel=info"
    volumes:
      - .:/app
      - ./static:/static
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             celery -A pastebinir beat --loglevel=info"
    volumes:
      - .:/app
      - ./static:/static
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - web

volumes:
  redis_data: 