volumes:
  production_django_media: {}
  production_django_static: {}
  production_redis_data: {}


services:
  django: &django
    build: 
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    volumes:
      - production_django_media:/app/media
      - production_django_static:/app/staticfiles
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - production_django_media:/usr/src/app/media:ro
      - production_django_static:/usr/src/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/privkey.pem
    depends_on:
      - django

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  celeryworker:
    <<: *django
    image: printir_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: printir_production_celerybeat
    command: /start-celerybeat

