#!/bin/bash

set -o errexit
set -o pipefail
# Remove nounset to allow undefined variables
# set -o nounset




# Set default values for database connection
if [ -z "${POSTGRES_USER:-}" ]; then
    export POSTGRES_USER="postgres"
fi

if [ -z "${POSTGRES_PASSWORD:-}" ]; then
    export POSTGRES_PASSWORD="postgres"
fi

# Handle both POSTGRES_DB and POSTGRES_NAME (for compatibility)
if [ -z "${POSTGRES_DB:-}" ]; then
    if [ -n "${POSTGRES_NAME:-}" ]; then
        export POSTGRES_DB="${POSTGRES_NAME}"
    else
        export POSTGRES_DB="postgres"
    fi
fi

if [ -z "${POSTGRES_HOST:-}" ]; then
    export POSTGRES_HOST="postgres"
fi

if [ -z "${POSTGRES_PORT:-}" ]; then
    export POSTGRES_PORT="5432"
fi

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python << END
import sys
import time

import psycopg

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
