#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Wait for PostgreSQL
python << END
import sys
import time

import psycopg

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

# Run Django development server with auto-reload
exec gunicorn pastebinir.wsgi:application \
    --bind 0.0.0.0:8000 \
    --workers 1 \
    --worker-class gevent \
    --log-level info \
    --log-file=- 